# Generated by Django 2.2.3 on 2020-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('target_base_uri', models.CharField(max_length=128)),
                ('api_name', models.CharField(max_length=255)),
                ('authentication', models.IntegerField(choices=[(0, 'Remote auth'), (1, 'Key auth'), (2, 'Basic auth')], default=0)),
                ('anonthrottlevalue', models.CharField(max_length=128)),
                ('anonthrottleunit', models.CharField(choices=[('s', 'Second'), ('m', 'Minute'), ('h', 'Hour'), ('d', 'Day')], default=0, max_length=10)),
                ('userthrottlevalue', models.CharField(max_length=128)),
                ('userthrottleunit', models.CharField(choices=[('s', 'Second'), ('m', 'Minute'), ('h', 'Hour'), ('d', 'Day')], default=0, max_length=10)),
            ],
        ),
    ]
